resources:
  - ../server-tls

namespace: <TERRASEC_NAMESPACE>

configMapGenerator:
  - name: ssh-known-hosts-config
    files:
      - known-hosts=.ssh/known_hosts

secretGenerator:
  - name: ssh-key-secret
    files:
      - private-key=.ssh/<SSH_KEY_NAME>

patchesStrategicMerge:
  - deployment-ssh-config.yaml
