apiVersion: apps/v1
kind: Deployment
metadata:
  name: terrasec
spec:
  template:
    spec:
      containers:
      - name: terrasec-server
        env:
        - name: K8S_WEBHOOK_API_KEY
          value: <WEBHOOK_API_KEY>
